# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2cb24cfb3c8636ee86c713effdfc05bf9c5724b71e6dc5c94fadd5fc85b6a72bcdc6f0bf84923e4f5a963cca752465a448856f7cb4199fe1f930c57b111d2062

test:
  secret_key_base: 68f757510839985a488a7e3932b9929ef187642c826744a9ff9d9a784c670cf4709f5f7156edb52d4d245a786177c1642bda9c2d952b971fff140333c3a2f4b2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
